### ISSUE TITLE
Support new3DS extra FCRAM

### ISSUE THREAD

**Issue by Wolfvak** [linux-3ds/linux#1]
The new3DS and new2DS systems have an extra 128 megabytes of FCRAM over the original model, starting at linear address `0x28000000`.

Register twiddling is needed to access this memory, this could be relegated to a bootloader or be a part of the init.
For reference, this is how it's done in GM9 https://github.com/d0k3/GodMode9/blob/ce50bd63a8c1fd1ede2e35d3a2a89085bcc22bde/arm11/source/system/sys.c#L55

**Comment by nickdesaulniers** [comment]
besides enabling it, how do we reconcile the current DT entry for
```
 48     fcram: memory@20000000 {                                                    
 49       device_type = "memory";                                                   
   50       reg = <0x20000000 0x08000000>;                                            
 51     }; 
```
?

**Comment by Wolfvak** [comment]
the new3DS ram is at the same base but extends to 256MiB, so 0x20000000 0x10000000

**Comment by profi200** [comment]
In case this was not known already the core 2/3 stuff also enables this FCRAM extension. More specifically switching to LGR(2) mode does. So this depends on #2.

See:
https://www.3dbrew.org/wiki/PDN_Registers#PDN_LGR_SOCMODE

**Comment by nickdesaulniers** [comment]
> For reference, this is how it's done in GM9

Oh, I just noticed that's done on the arm11 cores; for firm loader most of the bootloader runs on the arm9 core. Does that matter?

**Comment by Wolfvak** [comment]
Yes. The ARM11 bootloader will need to have a saner C runtime rather than being pure asm.

**Comment by nickdesaulniers** [comment]
@profi200 , is it possible to enable just the additional FCRAM, or must this be done in conjunction with enabling the additional cores?  I have the following implemented:
1. enable FCRAM/L2C via PDN_LGR_CNT
2. wait 403 cycles
3. set clk via PDN_LGR_SOCMODE to 804MHz

But when I adjust the device tree binding to say that we have double the amount of RAM we fail to boot.  Do I need to implement full support for the extra FCRAM and additional cores in order to boot either, or can FCRAM be enabled on its own?

I can boot my code without changing the device tree bindings; it will simply use half the available RAM, but does boot.  So I don't think I'm doing anything wrong per se in the bootloader, it's just that perhaps the kernel cannot use the additional memory at that point for some reason.

**Comment by profi200** [comment]
Yes, switching to some LGR2 mode is enough to enable the FCRAM extension. It's what homebrew like GodMode9 has been doing for a while. Make sure you are doing the proper wait for interrupt on **all** running cores. If you have core 1 in some wfe loop make sure it's wfi instead.

**Comment by nickdesaulniers** [comment]
Ah, so we do need to enable interrupts and wfi-spin until the changes take effect.  I have this working now, just going to clean up the code.

Before: 
![PXL_20210406_053207732](https://user-images.githubusercontent.com/1823839/113955001-c7bcdd80-97cf-11eb-9a7a-9e66a776b4ad.jpg)

After:
![PXL_20210408_013106467](https://user-images.githubusercontent.com/1823839/113955013-ce4b5500-97cf-11eb-8208-71c614e3ae95.jpg)

(open_agb_firm was an invaluable resource; I can't even imagine how much work went into that and all of the discovery that went into finding all of those values, thanks @profi200 and everyone that's helped!)
