### ISSUE TITLE
Support new3DS extra cores

### ISSUE THREAD

**Issue by Wolfvak** [linux-3ds/linux#2]
Similarly to #1, the new3DS supports two extra cores and they need a special initialization routine.
open_agb_firm already has a sample implementation, this should be done in the bootloader.
https://github.com/profi200/open_agb_firm/blob/1fcf024520571c9e8732a5aaaf1bbd7661cba423/source/arm11/hardware/pdn.c#L76

**Comment by profi200** [comment]
I was asked to describe the core 2/3 boot here.

First of all it didn't work reliably for me when other cores already have their MMU turned on. I dunno if this is a problem with the hardware design or [another bug](https://github.com/profi200/open_agb_firm/blob/kernel_experiments/source/arm11/hardware/interrupt.c#L177). Because of this problem you probably want to do this in the bootloader (arm9linuxfw). And importantly **ALL** CPU cores must enter wait for interrupt state while switching SoC mode/clock speed. This is explained below.

You first need to enable interrupt id 88 which is needed for this to work since the CPU cores can't wake up on their own from wfi state. Then you check which hardware this is running on and select the maximum clock based on that (line 79-80). There are 2 hardware variants called LGR and LGR2. LGR was a prototype that never got sold but has the same features and lower maximum clock.

You then turn on the L2 cache regs and the extra WRAM (used by the qtm system module for face recognition) (line 85-86) + a small delay to make sure changes take effect. In line 91 we change the SoC mode to LGR/LGR2 for the first time. Normally it's running in a compatibility mode to act like a regular 3DS SoC. This mode change is needed or the other cores won't boot. In line 95 we enable some hardware side fixes for the GPU to work in LGR(2) mode. Dunno why this is a reg and not enabled automatically on mode switch.

In line 98 we switch all periphals over to the newer revision/updated DMA-330 controller (all DMA requests will go to it instead of the old one). Next in line 103 we get core 2/3 into normal mode via the snoop control unit and switch temporarily into a lower speed mode but still keep the SoC in LGR(2) mode (line 106-114).

Then comes the complicated part. For some reason Nintendo made a all new SoC but didn't bother updating the bootrom which is needed because the bootrom traps all but core 0/1 in a infinity loop. Instead they implemented a hardware overlay feature that will make core 2/3 see different instruction/data when reading the bootrom area which enables us to make core 2/3 jump out of the bootrom. In line 116-132 we enable the overlay, get the cores out of reset, wait until they acknowledge they jumped to the core23Entry() function and disable the overlay.

The remaining is just normal software interrupts to tell core 2/3 and core 1 to jump to the proper entrypoint. Core 1 is waiting in the bootrom for a specific IRQ and will jump to the address stored at memory 0x1FFFFFDC.

Stuff you also wanna look at:
https://github.com/profi200/open_agb_firm/blob/kernel_experiments/include/arm11/hardware/cfg11.h
https://github.com/profi200/open_agb_firm/blob/kernel_experiments/include/arm11/hardware/pdn.h
https://www.3dbrew.org/wiki/CONFIG11_Registers
https://www.3dbrew.org/wiki/PDN_Registers

**Comment by nickdesaulniers** [comment]
OMG thank you! I've been going crazy trying to figure this out the past two days (trying to understand by reading through https://github.com/derrekr/fastboot3DS).

**Comment by profi200** [comment]
There are a few weird hardware choices that make Linux support a challenge. I think @Wolfvak knows best going almost insane porting/writing drivers. ;)

**Comment by xerpi** [comment]
Thanks @profi200 for the detailed explanation!
I agree, it's probably much better to do all of this in the bootloader.
Then at the end of the bootloader we can make the cores 1-3 (already initialized) spin in a wfi loop, waiting for core 0 to write the entry point to a custom location shared with Linux, such as `0x1FFFFFDC`, and then sending an IPI to wake them up.
This would also allow us to have a more "regular" SMP init on Linux, and the change to [`smp_cross_call`](https://github.com/linux-3ds/linux/commit/43af8e26420d52a1e2ac8a9a10fff93c0bc296a7#diff-dff1e6cff6ae05e9674bfa113a34894ab7180f80defe6d358e5242f349b2cec8L536) wouldn't be needed anymore, although it would limit the SMP compatibility to our bootloader.

**Comment by nickdesaulniers** [comment]
Is this the same thing as a "spin table," which device tree seems to have some documentation about?

**Comment by xerpi** [comment]
@nickdesaulniers Correct, that's the spin table.

**Comment by nickdesaulniers** [comment]
Ah I see @profi200 was refering to https://github.com/profi200/open_agb_firm/blob/1fcf024520571c9e8732a5aaaf1bbd7661cba423/source/arm11/hardware/pdn.c (specifically the kernel_experiments branch). I've added links to their comment.

> Because of this problem you probably want to do this in the bootloader (arm9linuxfw).

https://github.com/linux-3ds/firm_linux_loader is the bootloader, right?

> First of all it didn't work reliably for me when other cores already have their MMU turned on. I dunno if this is a problem with the hardware design or another bug.

Ah, I wonder if that's that was causing the lockup I was observing.

> Instead they implemented a hardware overlay feature

Heh, I wrote some code in TensorFlow's JIT compiler (XLA) for TPUs (in a previous life) to modify their overlays (which the TPU has) for allowing arbitrary control flow between large programs.  I guess the concept is much less foreign in the modern day than I'd had imagined!

Cool, https://www.kernel.org/doc/Documentation/arm64/booting.txt seems straightforward. I guess our "equivalent of `core23Entry`" would be the pen/loop and we'd add a memreserve DT entry.  I remember [Asahi Linux covered this](https://asahilinux.org/2021/03/progress-report-january-february-2021/) recently.

**Comment by profi200** [comment]
Yes, the open_agb_firm repo got more up to date driver code. I was actually planning to turn it into a lib at some point.
As for the bootloader i think https://github.com/linux-3ds/arm9linuxfw handles this all now. From uncompressing the kernel and booting it to talking with it to expose more hardware features. That's another challenge. Some hardware is not accessible by the ARM11 so we have to run some firmware on ARM9 that will give Linux access.

**Comment by xerpi** [comment]
@profi200 I was about to ask about this, turning open_agb_firm into a baremetal lib (and then make open_agb_firm use that lib) would be really useful for things like arm9linuxfw and the Linux FIRM loader :)

**Comment by xerpi** [comment]
Btw, I think arm9linuxfw is just the ARM9 FW, so it's actually the FIRM loader the one that acts as a small bootloader (it maps the framebuffer) for ARM11.
I think it would be better to rename arm9linuxfw to just: linuxfw or something like that, and also add the ARM11 bootloader code there, and also change FIRM loader to limit it to just boot arm11linuxbl.bin and arm9linuxfw.bin.

**Comment by Wolfvak** [comment]
I already added a new method to boot the secondary CPUs [here](https://github.com/linux-3ds/firm_linux_loader/commit/a599628e6a9ecf8e88fdfe5e16a6b024c1aafec5): the last 16 bytes of AXI WRAM will be used for the entrypoints.
the ARM11 part of the bootloader will have to perform all the initialization, including booting the secondary CPUs and have them execute a simple loop where they wait for the data at [0x1FFFFFF0 + (cpuid*4)] to be non-zero, then they branch to that value. there's also a wait for event to at least _attempt_ not to consume too much power.

on the ARM11 side it's as simple as writing a single value into memory and then sending an event

**Comment by profi200** [comment]
@xerpi 
Ah, thought this was all integrated into arm9linuxfw. Maybe it should be integrated into one for simplicity?

**Comment by profi200** [comment]
Fair enough. I doubt you can really get that performance in real world though. The bus is heavily bottlenecked whenever data crosses the bridge between the ARM9 side AHB bus and the ARM11 side AXI bus. The FCRAM is also quite slow.

If there is a way you wanna make Linux relocate the "hot" code from the FCRAM to AXIWRAM since that's quite a bit faster.

**Comment by nickdesaulniers** [comment]
I'll clean up the code tomorrow, but...
![PXL_20210414_062929860](https://user-images.githubusercontent.com/1823839/114664854-27742680-9cb1-11eb-81b8-466c1cda5b57.jpg)
![PXL_20210414_063032443](https://user-images.githubusercontent.com/1823839/114664855-28a55380-9cb1-11eb-8b8b-f5412e007c60.jpg)
![PXL_20210414_063044280](https://user-images.githubusercontent.com/1823839/114664857-28a55380-9cb1-11eb-8f4e-8cd9fc86c9c8.jpg)
