### ISSUE TITLE
Compilation instructions?

### ISSUE THREAD

**Issue by ParzivalWolfram** [linux-3ds/linux#4]
I've been following progress on Linux 3DS since I dropped it, and I was wondering what your procedure for compiling is, as I'm willing to test commits on my N3DSXL.

**Comment by nickdesaulniers** [comment]
```sh
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi make -j$(nproc) nintendo3ds_defconfig
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi make -j$(nproc)
$ ARCH=arm CROSS_COMPILE=arm-linux-gnueabi make -j$(nproc) nintendo3ds_ctr.dtb
```
see also [1](https://gbatemp.net/threads/release-linux-for-the-3ds.407187/), [2](https://gist.github.com/xerpi/3c720d345820691a2985502fcd80268f), [3](https://gist.github.com/xerpi/b4f7e02076497032ca83d2a9a2bbc8ae#file-make_3ds-sh).

**Comment by Wolfvak** [comment]
We will eventually release a buildroot system to compile the kernel + a small initramfs but as of right now you can disable the hardcoded rootfs directory and use the cpio from the original release.
Keeping this open until that happens.

**Comment by nickdesaulniers** [comment]
https://gist.github.com/xerpi/3c720d345820691a2985502fcd80268f#gistcomment-3684668 has directions for a basic buildroot image that works.  Just need to modify the dts file to tell it not to power down the machine immediately.

**Comment by nickdesaulniers** [comment]
I plan to rewrite the readme for each project with build steps.

**Comment by ParzivalWolfram** [comment]
I wonder if I could retool my old buildroot project for this kernel fork...

**Comment by ParzivalWolfram** [comment]
So I threw together a config that worked pretty well, but it died on final gen_initramfs.sh because [you hardcoded `/home/wolfvak/linux-3ds/rootfs` into it.](https://github.com/linux-3ds/linux/blob/43af8e26420d52a1e2ac8a9a10fff93c0bc296a7/arch/arm/configs/nintendo3ds_defconfig#L150)

**Comment by nickdesaulniers** [comment]
I think it would be better to keep the kernel build out of buildroot.  It's simpler the other way around IMO; build a buildroot image as an initrd, then place it in the kernel sources and leave it in the kernel tree as rootfs.cpio.gz.  The kernel build will produce the zImage with the ramdisk bundled.

I would create a separate git repo under this org that has a script and uses git submodules to clone all relevant sources, and orchestrate the build via shell scripts.  It would also be nice for us to provide prebuilt binaries, since most of the time during development not all pieces change and it's generally easier for users to test with those (though they can still use our build scripts if they want).

I think that's a better approach than including patch files for kernel sources in buildroot.  That won't scale when we break up the currently single commit for upstreaming.

**Comment by nickdesaulniers** [comment]
Since we don't want to pollute the linux dir with documentation (at this point, we can add documentations to Documentation/ at some point) for how to build or simply how to run this, do folks have thoughts on either approaches/ideas:

1. enable the wiki for this repo? This makes it quicker to edit/add/change, no commits or git necessary.
2. create a docs repo.  Can create a gh-pages branch to have github host a url for us.
3. collaborate with https://3ds.hacks.guide/, https://github.com/hacks-guide/Guide_3DS . Perhaps we should have something more polished first?

I think it would be good to have separate docs for fellow developers vs users that just want to run linux.  I guess they don't need to be separate per se. Thoughts?

**Comment by ParzivalWolfram** [comment]
Honestly, i'd be in favor of using the repo wiki. Too many repos will have build instructions, downloads, etc. in a gist or on some other page, which feels somewhat jarring, personally.

**Comment by nickdesaulniers** [comment]
SGTM. Yes gists aren't editable from others IIRC, so let's avoid those for documentation. @Wolfvak can you please enable wikis on all repos?

**Comment by Wolfvak** [comment]
Done

**Comment by ParzivalWolfram** [comment]
I can get Buildroot to spit out a zImage when I fix the hardcoded path in the defconfig, but it doesn't contain a rootfs. I'm not sure how to fix that, as Buildroot won't spit out a rootfs until well after you pass that point.

**Comment by nickdesaulniers** [comment]
right, because the kernel will fail to build because the kernel config says "look for rootfs.cpio.gz in the current working directory and include it in the build of the kernel."  When you build the kernel via buildroot, you're building these in the wrong order.  You need to build the buildroot image without building the kernel at all. Then you take the resulting rootfs.cpio.gz and put that in the kernel sources. Then you build the kernel.

**Comment by ParzivalWolfram** [comment]
> right, because the kernel will fail to build because the kernel config says "look for rootfs.cpio.gz in the current working directory and include it in the build of the kernel." When you build the kernel via buildroot, you're building these in the wrong order. You need to build the buildroot image without building the kernel at all. Then you take the resulting rootfs.cpio.gz and put that in the kernel sources. Then you build the kernel.

I tried that, since you stated to do it in the PR I made, but it still spits out a bad zImage.

**Comment by nickdesaulniers** [comment]
> but it still spits out a bad zImage.

If the rootfs.cpio.gz was not in the kernel sources, the kernel build should fail.

If the rootfs.cpio.gz is invalid, non-decompressable, or init is not executable, you should see a kernel panic (that's relatively good, at least the kernel image isn't bad).

===

I've now recompiled firm_linux_loader ([instructions](https://github.com/linux-3ds/firm_linux_loader/wiki) and arm9linuxfw ([instructions](https://github.com/linux-3ds/arm9linuxfw/wiki) and verified they work.

I haven't tried this fork of the kernel yet, maybe something is messed up there with that.  Let me verify and see if that's possibly the issue @ParzivalWolfram is hitting.

Where/how should I post binaries of what I have?

**Comment by ParzivalWolfram** [comment]
> If the rootfs.cpio.gz was not in the kernel sources, the kernel build should fail.
> 
> If the rootfs.cpio.gz is invalid, non-decompressable, or init is not executable, you should see a kernel panic (that's relatively good, at least the kernel image isn't bad, just the ramdisk is).
It's failing immediately on boot as it can't mount the rootfs. The rootfs i'm building is almost 23MB, the zImage that _should_ contain it is just over 5MB.

![20210331_002519](https://user-images.githubusercontent.com/30007617/113094739-dc89e780-91b7-11eb-8be0-6c0cf990bfdf.jpg)

**Comment by ParzivalWolfram** [comment]
This is my buildroot config. (For some reason, I have to hardcode the commit for the kernel header specifically, I can't just tell it to use the master branch like I can the kernel itself.)
[config.zip](https://github.com/linux-3ds/linux/files/6233978/config.zip)

**Comment by nickdesaulniers** [comment]
Please see:
1. the [Table of Contents](https://github.com/linux-3ds/linux/wiki/Table-of-Contents) linked from any project in this org's wikis.
2. the [twitch stream](https://www.twitch.tv/videos/983044002) I did this past weekend.

The directions will change more in the future, but we'll try to keep the wikis up to data. Might do more fomal HTML/MD pages. Might upload that twitch video to YT.
