### ISSUE TITLE
Learn with Pokémon: Typing Adventure Bluetooth support 

### ISSUE THREAD

**Issue by upintheairsheep** [linux-3ds/linux#93]
Can you add support for the Bluetooth chip inside of _Learn with Pokémon: Typing Adventure\_, as the game includes a [BCM2070](https://www.reddit.com/r/mildlyinteresting/comments/2srlx7/comment/cns9qz0/?utm_source=share&utm_medium=web2x&context=3) module and an antenna. The BCM2070 is supported within Linux already. The game's Bluetooth support, if implemented, will be enough to replace the necessity of WiFi support, and can connect whatever Bluetooth devices of your choosing to the console.

**Comment by ParzivalWolfram** [comment]
I don't think we currently have the cart bus hooked up in Linux yet, basic Bluetooth support doesn't allow for accessing the Internet for things like downloading source tarballs/binaries/packages or remote debugging, and I don't think this chip is going to be hooked up to allow for 100% unhindered access, as there's likely extra logic to support it and make the process of using it from the game easier. This would be neat to have eventually, but this would likely be harder to implement than would be feasible, and we'd need to have a framework to read and check for all game carts with extra hardware, assuming we can access them unhindered at all.

**Comment by upintheairsheep** [comment]
There I are a few Pokémon games that are more popular that includes IrDA,
but since the 3DS already had it I felt like i shouldn’t make another issue
since it would be infeasible, but those Pokémon games could replace a
damaged IrDA sensor.

**Comment by ParzivalWolfram** [comment]
> There I are a few Pokémon games that are more popular that includes IrDA, but since the 3DS already had it I felt like i shouldn’t make another issue since it would be infeasible, but those Pokémon games could replace a damaged IrDA sensor. The R4 microSD card can be supported as well.

Sorry, life hit me like a freight train and i've been inactive for a few months. This would be a nightmare to implement in general, and the benefits are pretty low. Not all R4 cards support external SD reading (mine definitely doesn't, it's one of the ones with the ntrboot switch. most of the ones that do support it are strictly cloning the first R4 line, which don't load at all on a DSi, much less a 3DS.) and the IrDA doesn't actually use the same frequencies as most PC IR adapters do (this issue is also present with the 3DS' built-in IR chipsets) so it's basically useless unless you're hooking them up to each other. As previously stated, this would be neat to have eventually, especially for things like cart dumping or save editing, but it's just not doable without finding multiple devs that can assist me on this project.
